### ISSUE TITLE
Telnet密码

### ISSUE THREAD

**Issue by jasonchio-cn** [captainTao/node#1]
GM220-S光猫用U盘备份的配置是.cfg文件 但是不知道是加密还是编码原因，打开是乱码，可以帮忙看看怎么获取telnet密码吗，telnet的用户名是 CMCCAdmin

**Comment by dropDBToRun** [comment]
礼问能解密吗

**Comment by ghost** [comment]
> GM220-S光猫用U盘备份的配置是.cfg文件 但是不知道是加密还是编码原因，打开是乱码，可以帮忙看看怎么获取telnet密码吗，telnet的用户名是 CMCCAdmin

你解开了吗
